//Image exists after entering data and generating
it('Input is seen in display container', () => {
  cy.visit('/line.html')
  cy.enterChartInfo()
  cy.findByText("Generate chart").click()
  cy.findByTestId("chart-display").find("img").should('exist')
})


it('Chart details are maintained when switching between all three pages of chart type', () => {
  cy.visit('/line.html')
  cy.enterChartInfo()
  cy.findByText("Generate chart").click()
  cy.visit('/scatter.html')
  cy.findByLabelText('Chart title').should('have.value', 'Test Chart')
  cy.findByLabelText('X label').should('have.value', "Time")
  cy.findByLabelText('Y label').should('have.value', 'Money')
  cy.findAllByLabelText('X').eq(0).should('have.value', '1')
  cy.findAllByLabelText('X').eq(1).should('have.value','2')
  cy.findAllByLabelText('X').eq(2).should('have.value','3')
  cy.findAllByLabelText('Y').eq(0).should('have.value','3')
  cy.findAllByLabelText('Y').eq(1).should('have.value','5')
  cy.findAllByLabelText('Y').eq(2).should('have.value','9')
  cy.visit('/bar.html')
  cy.findByLabelText('Chart title').should('have.value', 'Test Chart')
  cy.findByLabelText('X label').should('have.value', "Time")
  cy.findByLabelText('Y label').should('have.value', 'Money')
  cy.findAllByLabelText('X').eq(0).should('have.value', '1')
  cy.findAllByLabelText('X').eq(1).should('have.value','2')
  cy.findAllByLabelText('X').eq(2).should('have.value','3')
  cy.findAllByLabelText('Y').eq(0).should('have.value','3')
  cy.findAllByLabelText('Y').eq(1).should('have.value','5')
  cy.findAllByLabelText('Y').eq(2).should('have.value','9')
})